### ISSUE TITLE
[FEATURE] Allow port to be customised at runtime

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#11]
**Is your feature request related to a problem? Please describe.**
The port is currently hardcoded. While we've chosen a rather unique port number, there's always chance of conflict.

**Describe the solution you'd like**
Allow the port number to be customised via an environment variable, CLI flag, or both.

**Comment by premk** [comment]
I just reviewed #5. base_tests.go must also be refactored.

**Comment by hasyimibhar** [comment]
Highly recommend using this: https://github.com/ilyakaznacheev/cleanenv

**Comment by ashiquem** [comment]
> Highly recommend using this: https://github.com/ilyakaznacheev/cleanenv

Cool, looks neat will check it out. This looks pretty decent as well - https://github.com/joho/godotenv
