### ISSUE TITLE
[FEATURE] Logging, metrics, and alerting

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#12]
**Is your feature request related to a problem? Please describe.**
We need observability into the backend to understand how it's performing, and to troubleshoot issues in production.

**Describe the solution you'd like**
Investigate and implement an observability solution.

[Grafana](https://grafana.com/pricing/) and [Honeycomb](https://www.honeycomb.io/pricing/) are worth checking out. They both have decent free tiers.

**Describe alternatives you've considered**

**Additional context**

**Comment by hasyimibhar** [comment]
For the MVP, I recommend using something like NewRelic. It requires very little code to integrate with gin, and the free tier should be good enough for our scale.

**Comment by ilanbarshir** [comment]
I have also encountered [logz.io](https://logz.io/). They also have a free tier.

**Comment by rahulramkumar** [comment]
Self-hosted InfluxDB and Grafana is free option for dashboards and not that difficult to setup.

**Comment by baheckman** [comment]
NewRelic's free tier looks good for our use case: https://newrelic.com/pricing

**Comment by disposedtrolley** [comment]
It sounds like there are two broad approaches we can pursue:

### 1. Self hosting. Likely the Grafana stack.

This would require us to provision and maintain the stack on another VM (probably a DO Droplet). DO has Marketplace images for [Grafana](https://marketplace.digitalocean.com/apps/grafana) and [Loki](https://marketplace.digitalocean.com/apps/grafana-loki) but I'm unsure of the ongoing costs we'd need to commit to. @rahulramkumar are you able to shed some light on what ongoing maintenance looks like?

If the overhead is low enough, this option probably gives us the most flexibility and access to features that aren't in free tiers. That being said, I'm a little weary in self-hosting unless we have a good amount of expertise across the team.

### 2. The free tier of a SaaS like NewRelic, logz.io (hosted ELK), or even Grafana Cloud.

These are going to be largely set-and-forget. We'd want to pick an offering with a free tier that supports multiple users, decent log retention, and alerting since we won't be actively available 24/7 to monitor this thing. There's likely more criteria we should consider, so please chime in with your thoughts!

- NewRelic and logz offer unlimited users in the free tier, Grafana is limited to 3.
- NewRelic has 8 day retention, logz offers 1 day, Grafana is 14 days.
- NewRelic and Grafana offer unlimited alerts. Logz gives us 10.

Something else to think about is how we'll forward logs to these providers. DO App Platform has OOTB support for [log forwarding](https://docs.digitalocean.com/products/app-platform/how-to/forward-logs/) to some providers (none of which we've looked at here). Alternatively, we can probably easily run a log forwarder ourselves in the same container as the application.

**Comment by hasyimibhar** [comment]
Not sure if there has been discussions on what will be the scope for the MVP. But considering our limited resources in terms of manpower, I think we should definitely avoid self-hosting anything beside the API itself for the MVP. Self-hosting might seem cheap and easy, but it's actually expensive in terms of engineering hours required to maintain it over the long run. If something goes wrong (and it will!), someone has to be there to fix it, which might be unreasonable.

For the MVP, let's just focus on developing the product, and offload everything else to SaaS. In the worst case that the project loses steam and people lose interest in running it, at the very least we will still have observability working without requiring any maintenance work.

**Comment by baheckman** [comment]
> Something else to think about is how we'll forward logs to these providers. DO App Platform has OOTB support for [log forwarding](https://docs.digitalocean.com/products/app-platform/how-to/forward-logs/) to some providers (none of which we've looked at here). Alternatively, we can probably easily run a log forwarder ourselves in the same container as the application.

NewRelic has a Go api for instrumentation. I've not used it but I used the python one a few times and it was ok. Setup was pretty easy, just setting some environment variables for forwarding IIRC.
https://docs.newrelic.com/docs/apm/agents/go-agent/api-guides/guide-using-go-agent-api/

**Comment by disposedtrolley** [comment]
> Self-hosting might seem cheap and easy, but it's actually expensive in terms of engineering hours required to maintain it over the long run. If something goes wrong (and it will!), someone has to be there to fix it, which might be unreasonable.

Agreed. We won't have anyone "policing the police" either if we self host the observability stack.

> NewRelic has a Go api for instrumentation. I've not used it but I used the python one a few times and it was ok. 

I've used Datadog at work and this looks pretty similar. I'm surprised their free tier includes APM!

I'm happy to go with New Relic. What do folks think?

**Comment by disposedtrolley** [comment]
Got a little ahead of myself and gave New Relic a try. It was very painless to set up; their Go SDK has support for Gin middleware out of the box!
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/4476568/168748262-087edc01-a8e8-479f-b728-20c88d608901.png">

I've been pushing my progress [here](https://github.com/omshub/core-api/pull/14) if you want to take a look. I'll eventually do some refactoring and split the PR.

**Comment by baheckman** [comment]
> I've used Datadog at work and this looks pretty similar. I'm surprised their free tier includes APM!

I use datadog at work and personally prefer it hands down over newrelic (we cut over a few months ago and have never looked back), but NewRelic's free tier seems much better suited for our needs.

**Comment by disposedtrolley** [comment]
My work dropped NewRelic in favour of Datadog too haha. Ah well, hopefully we won't be spending too much time in NR to feel its annoyances.
