### ISSUE TITLE
[FEATURE] Structured logging to NewRelic

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#22]
**Is your feature request related to a problem? Please describe.**
DO App Platform can only forward logs to a [limited set of providers](https://docs.digitalocean.com/products/app-platform/how-to/forward-logs/), NewRelic not being one of them. If we were managing containers on a bare metal VM, we'd be able to install the [infrastructure agent](https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent) to tail and forward logs transparently.

**Describe the solution you'd like**
This is not ideal, but we should consider using the [Logs API](https://docs.newrelic.com/docs/logs/log-api/introduction-log-api/) to explicitly send logs to NewRelic. A structured logging library like [logrus](https://github.com/sirupsen/logrus) would provide us a means of transparently forwarding logs to NewRelic via a [hooks](https://github.com/sirupsen/logrus#hooks) mechanism.

We'll need to:

- add Logrus to the Go service.
- create a Logrus hook for logging to NewRelic.
- add Logrus middleware to Gin. There's no "official" middleware, but [this package](https://github.com/toorop/gin-logrus) looks very lightweight.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
