### ISSUE TITLE
Should we continue to vendor modules?

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#26]
We're currently vendoring Go modules which tends to result in substantial diffs in PRs that add or remove dependencies.

One advantage of vendoring is that we'll continue to have access to third party packages, even if their authors decide to delete the repository (**cough** left-pad). The disadvantage is the noise it can create in certain PRs.

I'm happy either way, but wanted to open this issue in case anyone had strong opinions on whether to vendor.

**Comment by kewellcjj** [comment]
ehh, so it's normal to have 400+ files modified in the vendor folder after I added two new packages, right?...

**Comment by awpala** [comment]
I think the jury is settled on this one; let's get rid of 'em! `famous last words`

**Comment by disposedtrolley** [comment]
Done https://github.com/omshub/core-api/pull/33
