### ISSUE TITLE
Wondering how to help? Start here!

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#29]
This document aims to give you an overview of the system we're trying to build and a sense of how its components work together, in an FAQ style. Much of this content should eventually make its way to the README (and probably a CONTRIBUTING.md).

---

## What are we building?

This repository contains the backend of OMShub, dubbed the "Core API". It also contains (temporarily) Terraform infrastructure-as-code definitions in the `ops/` subdirectory.

NB: some of the following is aspirational:

> The Core API is a Go service backed by a Postgres database, deployed onto DigitalOcean's [App Platform](https://docs.digitalocean.com/products/app-platform/) PaaS. It exposes a REST API defined with a [Swagger/OpenAPI specification](https://swagger.io/specification/) which the NextJS frontend queries. Users authenticate against the API using an OAuth 2.0 scheme, by supplying a bearer JWT issued by Auth0.

The Go service uses the [Gin framework](https://github.com/gin-gonic/gin) for routing and HTTP handling. It uses middleware to push basic metrics to NewRelic.

You can visit the hosted API at https://api.omshub.org.

This diagram shows roughly what we want to achieve:

```mermaid
graph LR;
    go(omshub/core-api)
    pg[(Postgres)]
    auth((Auth0))
    fe(omshub/website)
    oas(OpenAPI spec)
    tf((Terraform))
    gd((Google Domains))
    nr((NewRelic))
    user([User])

    style go fill:#f96,stroke:#333,stroke-width:4px
    style fe fill:#f96,stroke:#333,stroke-width:4px
    style user fill:#f9f,stroke:#333,stroke-width:4px

    user-->fe;
    user-->auth;

    subgraph DigitalOcean
        go <--> pg;
    end

    subgraph Terraform Cloud
        tf
    end

    subgraph Vercel
        fe
    end

    auth--"provides user login for"-->fe;
    fe--"calls"-->go;
    tf--"provisions infra for"-->go;
    tf--"configures"-->auth;
    tf--"deploys"-->pg;
    gd--"routes api.omshub.org to"-->go;

    go--"sends metrics and logs"-->nr;
    oas--"implemented by"-->go;
    fe--"consults"-->oas;
```

### What are the most pressing issues to help with?

- Creating an OpenAPI specification. There's an [outstanding issue](https://github.com/omshub/core-api/issues/9) to look at go-swagger or Goa to manage the OpenAPI lifecycle. @baheckman is taking point on this.
- Setting up the connection between the Go service and Postgres using https://gorm.io. @kewellcjj is looking into this.
- Investigating how we might authenticate API requests. Auth0 is the vendor of choice, but we haven't signed up for an account yet nor spiked anything out.
- Adding structured logging to NewRelic. https://github.com/omshub/core-api/issues/22

Feel free to pick up any of these issues, but **please make sure to document your intention by creating a GitHub issue and assigning yourself to it**. This gives everyone the opportunity to provide input and ensures people don't double up on tasks. There is no expectation of commitment, but we ask that you please comment in the issue if you're unable to continue with the task so someone else can continue the work.

### Where do I go for help?

- [#team-site-back-end](https://discord.com/channels/973924367140528128/973928969592246272)
- [#team-site-ci-cd-devops](https://discord.com/channels/973924367140528128/973929060591874048)
- [#team-site-security-auth](https://discord.com/channels/973924367140528128/973929163272626207)

## How does deployment work?

Terraform will automatically provision any required infrastructure changes (this should only happen if something under `ops/` is modified) when a PR is merged. Following a successful Terraform apply, the Go service will be deployed to DigitalOcean.

Tip: the Terraform workflow will comment on your PR with an overview of any infrastructure changes that are needed.

## What external systems do I need access to?

- We use **NewRelic** for metrics and logging. Basic users can be provisioned free of charge. Please
  message [#team-site-back-end](https://discord.com/channels/973924367140528128/973928969592246272)
  on Discord for access.
- The Go service and Postgres database are provisioned on **DigitalOcean**. The entire deployment proces
  is handled by Terraform and GitHub Actions, so you typically won't need access to DigitalOcean
  directly.
- Infrastructure is managed by Terraform, and **Terraform Cloud** is being used as the state backend.
  Terraform is almost wholly managed via the `ops/` folder and GitHub Actions, so access is typically
  not required.

**Comment by awpala** [comment]
**TO JOIN THE DISCORD SERVER**: Please follow the invite link [here](https://discord.gg/3RPvy2n9). This may also be necessary in order to access the channel links above FYI.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
