### ISSUE TITLE
[FEATURE] Complete the basic DB schema

### ISSUE THREAD

**Issue by kewellcjj** [omshub/core-api#36]
A good example is given in https://github.com/omshub/website/issues/1#issuecomment-1123152068, which will need some further discussion. See https://github.com/omshub/core-api/blob/main/internal/api/db/models/review.go and https://github.com/omshub/core-api/blob/main/internal/api/handlers/review.go for implementation.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
