### ISSUE TITLE
[FEATURE] Intercept OS signals to shutdown the server gracefully

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#6]
**Is your feature request related to a problem? Please describe.**

We're not currently listening to OS signals and shutting the server down gracefully. This can lead to abruptly closing connections to clients and leaving open file handles on the system.

**Describe the solution you'd like**

Task a goroutine in the `main` entrypoint to listen for SIGINT and SIGTERM, and invoke the server's `Shutdown` method if they occur. We can probably follow the [Gin example here](https://github.com/gin-gonic/examples/blob/master/graceful-shutdown/graceful-shutdown/notify-with-context/server.go).

**Additional context**

https://github.com/omshub/core-api/pull/5 should be merged prior to starting this work, as the server interface has been improved.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
