### ISSUE TITLE
[FEATURE] Run Gin in release mode in production deploy

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#7]
**Describe the solution you'd like**

Nothing to action right now, but leaving this here to remind us to set the `GIN_MODE` environment variable to `release` if we're running in production.

We won't need to worry about this for a while (at least until we've decided on how this will be packaged and hosted).

**Additional context**

[Why we should set the gin.Mode?](https://github.com/gin-gonic/gin/issues/2984)

**Comment by disposedtrolley** [comment]
This involves adding a new environment variable to the DO app's Terraform config.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
