### ISSUE TITLE
[FEATURE] Embed build information into the binary using linker flags 

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#8]
**Describe the solution you'd like**
Consider embedding build information (like the commit SHA) into the binary via [linker flags](https://www.digitalocean.com/community/tutorials/using-ldflags-to-set-version-information-for-go-applications). This can be useful as an audit trail and for debugging purposes, as the source tree isn't typically pushed to the hosting provider for Go applications.

We need to decide on the information to embed. The commit SHA is probably a good place to start.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
