### ISSUE TITLE
[FEATURE] Use Goa to design and generate the API

### ISSUE THREAD

**Issue by disposedtrolley** [omshub/core-api#9]
**Is your feature request related to a problem? Please describe.**
One of the drawbacks of decoupling the backend from the [NextJS app](https://github.com/omshub/website) is the need to design and maintain an explicit API contract between the two services.

- It's very easy to accidentally make a breaking change that renders the frontend inoperable.
- We can't easily parallelise the work streams if the frontend folks are blocked waiting for the backend to be finished.
- The frontend can make incorrect assumptions of the API being exposed, leading to integration issues.

**Describe the solution you'd like**
Use [Goa](https://goa.design) to design the API and generative service code. This approach has many advantages:

- Changing the API results in a broken build and vice versa. This ensures we are intentional and mindful when we make changes.
- Can automatically produce an [OpenAPI](https://swagger.io/specification/) definition, which can be used by the frontend teams to autogenerate clients and mocks. This is incredibly useful during the initial phases of development; we can decouple our implementation work entirely from the frontend.
- We get automatically generated structs, serialisation, deserialisation, and validation logic for the resources we expose.
- The DSL is easy to read and forms part of the living documentation of this service.
- Can generate a client that's preconfigured to make requests to the server (i.e. self-contained Postman).

To start with, we can design and generate the code for the ping and index routes, and wire them up to the Gin router.

**Describe alternatives you've considered**
Manually maintain an OpenAPI spec that the frontend can build against. This introduces maintenance and testing overhead, and would likely require us to create a comprehensive set of contract tests independent of the service.

**Additional context**
- Note that since we're vendoring modules, we need to follow [this step](https://github.com/goadesign/goa#troubleshooting) to ensure Goa will work.
- We can probably continue using Gin and plug in the handlers that Goa generates. See this [example](https://github.com/goadesign/examples/blob/master/basic/gen/http/calc/server/server.go#L20-L24), where Goa has generated a server struct with `http.Handler` fields for each operation defined in the DSL.

**Comment by disposedtrolley** [comment]
@baheckman [recommended](https://discord.com/channels/973924367140528128/976990486680203314/976993993588092978) we give go-swagger a try! I think any tool is sufficient so long as it enables us to tie the implementation with the API spec.

**Comment by awpala** [comment]
Closing for obsolescence. Repo is deprecated/inactive as of July 2022.
